import "server-only";
import { mockDelay } from "@/bootstrap/lib/mock";
import type { AuditEvent } from "../../domain/entities/audit-event.entity";
import type { AuditLogFilter } from "../../domain/entities/audit-log-filter.entity";
import type {
  AuditLogPageResult,
  AuditLogResult,
  IAuditLogRepository,
} from "../../domain/repositories/i-audit-log.repository";

/**
 * In-memory audit-log seed (US-E12.12, mock-first per decision 0014). Adapted
 * from design_src/edu/audit-log.jsx for realism — names / labels / reasons are
 * mock *data*, not i18n copy. Actions reconciled to the fe-lead ruling union
 * (CREATE/UPDATE/DELETE/APPROVE/LOCK/SEAL/UNSEAL); spans all four entity types
 * and a June-2026 date range so filter + pagination combinations are exercised.
 */
export const AUDIT_LOG_SEED: AuditEvent[] = [
  {
    id: "log-1041",
    occurredAt: "2026-06-13T09:42:11.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "UNSEAL",
    entityType: "record",
    entityId: "rec-phamhuuphuc-hk2-24-25",
    entityLabel: "Học bạ · HK2 · 2024-2025 — Phạm Hữu Phúc",
    beforeValue: "sealed",
    afterValue: "open",
  },
  {
    id: "log-1040",
    occurredAt: "2026-06-13T08:15:03.000Z",
    actorId: "tch-1",
    actorName: "Nguyễn Thị Hương",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-12c1-math-ck-001",
    entityLabel: "Toán · Cuối kỳ — Lê Hoàng Nhật",
    beforeValue: "8.5",
    afterValue: "9.0",
  },
  {
    id: "log-1039",
    occurredAt: "2026-06-12T16:30:47.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "LOCK",
    entityType: "grade",
    entityId: "batch-12c1-math-hk1",
    entityLabel: "Toán · 12C1 · HK1",
    beforeValue: "open",
    afterValue: "locked",
  },
  {
    id: "log-1038",
    occurredAt: "2026-06-12T16:05:22.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "APPROVE",
    entityType: "grade",
    entityId: "batch-12c1-math-hk1",
    entityLabel: "Toán · 12C1 · HK1",
    beforeValue: "pending",
    afterValue: "approved",
  },
  {
    id: "log-1037",
    occurredAt: "2026-06-12T15:48:09.000Z",
    actorId: "tch-1",
    actorName: "Nguyễn Thị Hương",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-11b2-math-gk-006",
    entityLabel: "Toán · Giữa kỳ — Trần Quốc Việt",
    beforeValue: "6.0",
    afterValue: "7.0",
  },
  {
    id: "log-1036",
    occurredAt: "2026-06-12T14:20:18.000Z",
    actorId: "tch-9",
    actorName: "Nguyễn Văn Phúc",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "conduct",
    entityId: "conduct-10a1-pd",
    entityLabel: "Hạnh kiểm · HK1 — Phạm Đức Dũng",
    beforeValue: "Trung bình",
    afterValue: "Khá",
  },
  {
    id: "log-1035",
    occurredAt: "2026-06-12T11:55:00.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "SEAL",
    entityType: "record",
    entityId: "rec-lehoangnhat-hk1-25-26",
    entityLabel: "Học bạ · HK1 · 2025-2026 — Lê Hoàng Nhật",
    beforeValue: "open",
    afterValue: "sealed",
  },
  {
    id: "log-1034",
    occurredAt: "2026-06-12T11:54:48.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "SEAL",
    entityType: "record",
    entityId: "rec-dinhquynh-hk1-25-26",
    entityLabel: "Học bạ · HK1 · 2025-2026 — Đinh Thị Quỳnh",
    beforeValue: "open",
    afterValue: "sealed",
  },
  {
    id: "log-1033",
    occurredAt: "2026-06-12T09:10:32.000Z",
    actorId: "admin-2",
    actorName: "Lê Thị Mai",
    actorRole: "admin",
    action: "DELETE",
    entityType: "grade",
    entityId: "gr-11a1-eng-tx1-009",
    entityLabel: "Tiếng Anh · TX1 — Đặng Thuỳ Linh (nhập trùng)",
    beforeValue: "7.5",
    afterValue: null,
  },
  {
    id: "log-1032",
    occurredAt: "2026-06-11T17:02:14.000Z",
    actorId: "tch-2",
    actorName: "Trần Văn Minh",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-11b2-phy-tx2-004",
    entityLabel: "Vật Lý · TX2 — Mai Thu Hà",
    beforeValue: "7.0",
    afterValue: "8.0",
  },
  {
    id: "log-1031",
    occurredAt: "2026-06-11T14:30:00.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "LOCK",
    entityType: "grade",
    entityId: "batch-11b2-math-hk1",
    entityLabel: "Toán · 11B2 · HK1",
    beforeValue: "open",
    afterValue: "locked",
  },
  {
    id: "log-1030",
    occurredAt: "2026-06-11T09:00:42.000Z",
    actorId: "tch-3",
    actorName: "Lê Thị Hoa",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-10a1-chem-gk-002",
    entityLabel: "Hoá Học · GK — Trần Văn Bình",
    beforeValue: "6.5",
    afterValue: "7.5",
  },
  {
    id: "log-1029",
    occurredAt: "2026-06-10T22:14:55.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "UPDATE",
    entityType: "conduct",
    entityId: "conduct-12c1-hn",
    entityLabel: "Hạnh kiểm · HK1 — Hoàng Văn Nam",
    beforeValue: "Yếu",
    afterValue: "Trung bình",
  },
  {
    id: "log-1028",
    occurredAt: "2026-06-10T16:22:01.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "APPROVE",
    entityType: "grade",
    entityId: "batch-10a1-chem-hk1",
    entityLabel: "Hoá · 10A1 · HK1",
    beforeValue: "pending",
    afterValue: "approved",
  },
  {
    id: "log-1027",
    occurredAt: "2026-06-10T10:42:11.000Z",
    actorId: "tch-1",
    actorName: "Nguyễn Thị Hương",
    actorRole: "teacher",
    action: "CREATE",
    entityType: "grade",
    entityId: "gr-10a1-math-gk-008",
    entityLabel: "Toán · Giữa kỳ — Bùi Minh Tuấn",
    beforeValue: null,
    afterValue: "6.0",
  },
  {
    id: "log-1026",
    occurredAt: "2026-06-09T18:45:09.000Z",
    actorId: "admin-2",
    actorName: "Lê Thị Mai",
    actorRole: "admin",
    action: "UNSEAL",
    entityType: "record",
    entityId: "rec-tranqviet-hk1-24-25",
    entityLabel: "Học bạ · HK1 · 2024-2025 — Trần Quốc Việt",
    beforeValue: "sealed",
    afterValue: "open",
  },
  {
    id: "log-1025",
    occurredAt: "2026-06-09T11:08:54.000Z",
    actorId: "tch-5",
    actorName: "Đỗ Thị Mai",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-11a1-eng-ck-003",
    entityLabel: "Tiếng Anh · CK — Đặng Thuỳ Linh",
    beforeValue: "8.5",
    afterValue: "9.0",
  },
  {
    id: "log-1024",
    occurredAt: "2026-06-09T08:00:00.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "UPDATE",
    entityType: "setting",
    entityId: "setting-grade-scale",
    entityLabel: "Thang điểm · Toàn trường",
    beforeValue: "Thang 10",
    afterValue: "Thang 10 (làm tròn 0.25)",
  },
  {
    id: "log-1023",
    occurredAt: "2026-06-08T15:30:18.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "LOCK",
    entityType: "grade",
    entityId: "batch-11b2-lit-hk1",
    entityLabel: "Văn · 11B2 · HK1",
    beforeValue: "open",
    afterValue: "locked",
  },
  {
    id: "log-1022",
    occurredAt: "2026-06-08T09:14:00.000Z",
    actorId: "tch-1",
    actorName: "Nguyễn Thị Hương",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "conduct",
    entityId: "conduct-11b2-vb",
    entityLabel: "Hạnh kiểm · HK1 — Vũ Quốc Bảo",
    beforeValue: "Khá",
    afterValue: "Tốt",
  },
  {
    id: "log-1021",
    occurredAt: "2026-06-07T17:00:00.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "APPROVE",
    entityType: "grade",
    entityId: "batch-11b2-phy-hk1",
    entityLabel: "Lý · 11B2 · HK1",
    beforeValue: "pending",
    afterValue: "approved",
  },
  {
    id: "log-1020",
    occurredAt: "2026-06-07T09:33:21.000Z",
    actorId: "tch-4",
    actorName: "Phạm Quốc Bảo",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-10a2-his-ck-005",
    entityLabel: "Lịch Sử · CK — Trần Khải An",
    beforeValue: "7.0",
    afterValue: "7.5",
  },
  {
    id: "log-1019",
    occurredAt: "2026-06-06T14:00:00.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "UNSEAL",
    entityType: "record",
    entityId: "rec-lethicam-hk2-23-24",
    entityLabel: "Học bạ · HK2 · 2023-2024 — Lê Thị Cẩm",
    beforeValue: "sealed",
    afterValue: "open",
  },
  {
    id: "log-1018",
    occurredAt: "2026-06-06T10:21:46.000Z",
    actorId: "tch-1",
    actorName: "Nguyễn Thị Hương",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-10a1-math-tx1-005",
    entityLabel: "Toán · TX1 — Hoàng Thị Linh",
    beforeValue: "8.0",
    afterValue: "8.5",
  },
  {
    id: "log-1017",
    occurredAt: "2026-06-05T22:08:30.000Z",
    actorId: "tch-9",
    actorName: "Nguyễn Văn Phúc",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "conduct",
    entityId: "conduct-10a1-pd-2",
    entityLabel: "Hạnh kiểm · HK1 — Phạm Đức Dũng",
    beforeValue: "Yếu",
    afterValue: "Trung bình",
  },
  {
    id: "log-1016",
    occurredAt: "2026-06-05T16:42:09.000Z",
    actorId: "tch-4",
    actorName: "Phạm Quốc Bảo",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-11b2-lit-gk-001",
    entityLabel: "Văn · GK — Phan Anh Khoa",
    beforeValue: "7.5",
    afterValue: "8.0",
  },
  {
    id: "log-1015",
    occurredAt: "2026-06-05T11:20:55.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "APPROVE",
    entityType: "grade",
    entityId: "batch-11a1-eng-hk1",
    entityLabel: "Anh · 11A1 · HK1",
    beforeValue: "pending",
    afterValue: "approved",
  },
  {
    id: "log-1014",
    occurredAt: "2026-06-04T09:14:32.000Z",
    actorId: "tch-1",
    actorName: "Nguyễn Thị Hương",
    actorRole: "teacher",
    action: "CREATE",
    entityType: "grade",
    entityId: "gr-12c1-math-ck-005",
    entityLabel: "Toán · CK — Bùi Tuấn Kiệt",
    beforeValue: null,
    afterValue: "6.0",
  },
  {
    id: "log-1013",
    occurredAt: "2026-06-03T15:12:03.000Z",
    actorId: "admin-2",
    actorName: "Lê Thị Mai",
    actorRole: "admin",
    action: "UPDATE",
    entityType: "setting",
    entityId: "setting-conduct-rubric",
    entityLabel: "Tiêu chí hạnh kiểm · Khối 12",
    beforeValue: "Rubric v1",
    afterValue: "Rubric v2",
  },
  {
    id: "log-1012",
    occurredAt: "2026-06-03T08:40:19.000Z",
    actorId: "tch-3",
    actorName: "Lê Thị Hoa",
    actorRole: "teacher",
    action: "DELETE",
    entityType: "conduct",
    entityId: "conduct-10a1-tvb-draft",
    entityLabel: "Hạnh kiểm · nháp — Trần Văn Bình (nhập nhầm)",
    beforeValue: "Trung bình",
    afterValue: null,
  },
  {
    id: "log-1011",
    occurredAt: "2026-06-02T13:55:47.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "SEAL",
    entityType: "record",
    entityId: "rec-hoangvannam-hk1-25-26",
    entityLabel: "Học bạ · HK1 · 2025-2026 — Hoàng Văn Nam",
    beforeValue: "open",
    afterValue: "sealed",
  },
  {
    id: "log-1010",
    occurredAt: "2026-06-02T10:05:33.000Z",
    actorId: "tch-5",
    actorName: "Đỗ Thị Mai",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-11a1-eng-gk-007",
    entityLabel: "Tiếng Anh · GK — Vũ Quốc Bảo",
    beforeValue: "6.5",
    afterValue: "7.0",
  },
  {
    id: "log-1009",
    occurredAt: "2026-06-01T16:20:00.000Z",
    actorId: "admin-1",
    actorName: "Trần Minh Quân",
    actorRole: "admin",
    action: "CREATE",
    entityType: "setting",
    entityId: "setting-term-weights",
    entityLabel: "Trọng số điểm · Năm học 2025-2026",
    beforeValue: null,
    afterValue: "TX 15% · GK 25% · CK 60%",
  },
  {
    id: "log-1008",
    occurredAt: "2026-06-01T09:02:41.000Z",
    actorId: "tch-2",
    actorName: "Trần Văn Minh",
    actorRole: "teacher",
    action: "UPDATE",
    entityType: "grade",
    entityId: "gr-11b2-phy-ck-002",
    entityLabel: "Vật Lý · CK — Trần Quốc Việt",
    beforeValue: "5.5",
    afterValue: "6.5",
  },
  {
    id: "log-1007",
    occurredAt: "2026-05-30T14:48:12.000Z",
    actorId: "admin-2",
    actorName: "Lê Thị Mai",
    actorRole: "admin",
    action: "LOCK",
    entityType: "grade",
    entityId: "batch-10a2-his-hk1",
    entityLabel: "Lịch Sử · 10A2 · HK1",
    beforeValue: "open",
    afterValue: "locked",
  },
  {
    id: "log-1006",
    occurredAt: "2026-05-28T11:33:58.000Z",
    actorId: "tch-4",
    actorName: "Phạm Quốc Bảo",
    actorRole: "teacher",
    action: "CREATE",
    entityType: "conduct",
    entityId: "conduct-10a2-tka",
    entityLabel: "Hạnh kiểm · HK1 — Trần Khải An",
    beforeValue: null,
    afterValue: "Khá",
  },
];

/** Encode/decode an opaque offset cursor — cursor stays infra-only. */
function encodeCursor(offset: number): string {
  return `offset:${offset}`;
}
function decodeCursor(cursor: string | null): number {
  if (!cursor) return 0;
  const parsed = Number.parseInt(cursor.replace(/^offset:/, ""), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
}

function matches(event: AuditEvent, filter: AuditLogFilter): boolean {
  if (filter.entityType && event.entityType !== filter.entityType) return false;
  if (filter.action && event.action !== filter.action) return false;
  if (filter.actorQuery?.trim()) {
    const q = filter.actorQuery.trim().toLowerCase();
    if (!event.actorName.toLowerCase().includes(q)) return false;
  }
  const day = event.occurredAt.slice(0, 10);
  if (filter.from && day < filter.from) return false;
  if (filter.to && day > filter.to) return false;
  return true;
}

/**
 * Mock audit-log repository (US-E12.12). Synchronous in-memory filter + offset
 * cursor slicing over a fresh copy of the seed. Newest-first ordering.
 */
export class MockAuditLogRepository implements IAuditLogRepository {
  // Sorted newest-first once per instance (fresh copy for determinism).
  private readonly events: AuditEvent[] = [...AUDIT_LOG_SEED].sort((a, b) =>
    a.occurredAt < b.occurredAt ? 1 : a.occurredAt > b.occurredAt ? -1 : 0,
  );

  async getAuditLog(
    filter: AuditLogFilter,
    cursor: string | null,
    limit: number,
  ): Promise<AuditLogResult<AuditLogPageResult>> {
    await mockDelay();
    const filtered = this.events.filter((e) => matches(e, filter));
    const offset = decodeCursor(cursor);
    const slice = filtered.slice(offset, offset + limit);
    const nextOffset = offset + slice.length;
    const hasMore = nextOffset < filtered.length;
    return {
      ok: true,
      value: {
        events: slice.map((e) => ({ ...e })),
        nextCursor: hasMore ? encodeCursor(nextOffset) : null,
        hasMore,
      },
    };
  }
}
